---
  elas:
    hosts:
      elas01:
        ansible_host: 192.168.88.16
        ansible_connection: ssh
        ansible_user: root
  kiba:
    hosts:
      kiba01:
        ansible_host: 192.168.88.15
        ansible_connection: ssh
        ansible_user: root